### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Badding** [PyryL/toothpaste#15]
Nicely designed and implemented application! The code was clearly written and executed. 

-Good documentation and instructions.
-The functionality is divided into suitable files.
-Simple and clear front-end

Overall, it's really great. It was educational to review your app!

Issues:
-I had trouble making a new account. Couldn't get pass the username/password requirements with any username/ password combo. If I'm not mistaken, a password like 'ASDdfg123!'# should meet the requirements. I couldn't test all the features because of this."
-You are able to send empty messages

**Comment by PyryL** [comment]
Thanks for the feedback and sharp points! Bugs have now been fixed in the referenced commits above.
